A2/A2/Controllers/FeedbackCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using A2.Data;
using A2.Models;

namespace A2.Controllers
{
    public class FeedbackCategoriesController : Controller
    {
        private A2Context db = new A2Context();

        // GET: Categories
        public ActionResult Index()
        {
            return View(db.FeedbackCategories.OrderBy(c => c.Name).ToList());
        }

        // GET: FeedbackCategories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FeedbackCategory feedbackCategory = db.FeedbackCategories.Find(id);
            if (feedbackCategory == null)
            {
                return HttpNotFound();
            }
            return View(feedbackCategory);
        }

        // GET: FeedbackCategories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FeedbackCategories/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] FeedbackCategory feedbackCategory)
        {
            if (ModelState.IsValid)
            {
                db.FeedbackCategories.Add(feedbackCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(feedbackCategory);
        }

        // GET: FeedbackCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FeedbackCategory feedbackCategory = db.FeedbackCategories.Find(id);
            if (feedbackCategory == null)
            {
                return HttpNotFound();
            }
            return View(feedbackCategory);
        }

        // POST: FeedbackCategories/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] FeedbackCategory feedbackCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(feedbackCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(feedbackCategory);
        }

        // GET: FeedbackCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FeedbackCategory feedbackCategory = db.FeedbackCategories.Find(id);
            if (feedbackCategory == null)
            {
                return HttpNotFound();
            }
            return View(feedbackCategory);
        }

        // POST: FeedbackCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FeedbackCategory feedbackCategory = db.FeedbackCategories.Find(id);
            db.FeedbackCategories.Remove(feedbackCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult ViewPage0()
        {
            return View();

        }
        public ActionResult ViewPage1()
        {
            return View();

        }
        public ActionResult ViewPage2()
        {
            return View();

        }
    }
}

A2/A2/Controllers/FeedbacksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using A2.Data;
using A2.Models;
using A2.ViewModels;

namespace A2.Controllers
{
    public class FeedbacksController : Controller
    {
        private A2Context db = new A2Context();

        // GET: Products
        public ActionResult Index(string category, string search)
        {
            //instantiate a new view model
            FeedbackIndexViewModel viewModel = new FeedbackIndexViewModel();
            var products = db.Feedbacks.Include(p => p.FeedbackCategory);
            //find the products where either the product name field contains search,the product 
            //description contains search, or the product's category name contains search
            if (!String.IsNullOrEmpty(search))
            {
                products = products.Where(p => p.Name.Contains(search) ||
                p.Description.Contains(search) ||
                p.FeedbackCategory.Name.Contains(search));
                // ViewBag.Search = search;
                viewModel.Search = search;
            }
            //group search results into categories and count how many items in each category
            viewModel.CatsWithCount = from matchingProducts in products
                                      where
                                      matchingProducts.FeedBackCategoryID != null
                                      group matchingProducts by
                                      matchingProducts.FeedbackCategory.Name into
                                      catGroup
                                      select new CategoryWithCount()
                                      {
                                          CategoryName = catGroup.Key,
                                          ProductCount = catGroup.Count()
                                      };
            //var categories = products.OrderBy(p => p.Category.Name).Select(p => p.FeedbackCategory.Name).Distinct();
            if (!String.IsNullOrEmpty(category))
            {
                products = products.Where(p => p.FeedbackCategory.Name == category);
            }
            //ViewBag.Category = new SelectList(categories); 
            viewModel.Feedbacks = products;
            // return View(products.ToList());
            return View(viewModel);
        }

        // GET: Feedbacks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feedback feedback = db.Feedbacks.Find(id);
            if (feedback == null)
            {
                return HttpNotFound();
            }
            return View(feedback);
        }

        // GET: Feedbacks/Create
        public ActionResult Create()
        {
            ViewBag.FeedBackCategoryID = new SelectList(db.FeedbackCategories, "ID", "Name");
            return View();
        }

        // POST: Feedbacks/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Description,FeedBackCategoryID")] Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                db.Feedbacks.Add(feedback);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FeedBackCategoryID = new SelectList(db.FeedbackCategories, "ID", "Name", feedback.FeedBackCategoryID);
            return View(feedback);
        }

        // GET: Feedbacks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feedback feedback = db.Feedbacks.Find(id);
            if (feedback == null)
            {
                return HttpNotFound();
            }
            ViewBag.FeedBackCategoryID = new SelectList(db.FeedbackCategories, "ID", "Name", feedback.FeedBackCategoryID);
            return View(feedback);
        }

        // POST: Feedbacks/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Description,FeedBackCategoryID")] Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                db.Entry(feedback).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FeedBackCategoryID = new SelectList(db.FeedbackCategories, "ID", "Name", feedback.FeedBackCategoryID);
            return View(feedback);
        }

        // GET: Feedbacks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feedback feedback = db.Feedbacks.Find(id);
            if (feedback == null)
            {
                return HttpNotFound();
            }
            return View(feedback);
        }

        // POST: Feedbacks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Feedback feedback = db.Feedbacks.Find(id);
            db.Feedbacks.Remove(feedback);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult ViewPage0()
        {
            return View();

        }
        public ActionResult ViewPage1()
        {
            return View();

        }
        public ActionResult ViewPage2()
        {
            return View();

        }
    }
}

A2/A2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Yi Nationality", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="切换导航" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Types of Suggesion", "Index", "FeedbackCategories", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Suggestion Box", "Index", "Feedbacks", new { area = "" }, new { @class = "nav-link" })</li>

                </ul>

                @using (Html.BeginForm("Index", "Feedbacks", FormMethod.Get, new
                {
                    @class =
                "zujian"
                }))
                {
                    <div class="form-group">
                        @Html.TextBox("Search", null, new
                        {
                            @class = "change1",
                            @placeholder =
                        "Search Suggestion"
                        })
                    </div>
                    <div class="form-group"><button type="submit" class="change">Submit</button></div>
                }
                

                <div class="introduce">
                    <ul>
                        <li><a href="/Home/ViewPage0">Home</a></li>
                        <li><a href="/Home/ViewPage1">Traditional Culture</a></li>
                        <li><a href="/Home/ViewPage2">Natural Scenery</a></li>
                        <li class="four">@Html.ActionLink(" Suggestion", "Index", "Feedbacks")</li>

                    </ul>

                </div>
            </div>
            </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="introduceL">
                <p class="intL1">
                    Producer：YuXin Zhang
                </p>
                <p class="intL2">
                    <a href="tel:XXXXXX">Contact information:XXXXXX</a>
                </p>
           
                <p class="intL3">
                    <a href="mailto:">E-mail：Have_a_nice_day@qq.com</a>
                </p>
            </div>
            <div class="introduceR">
                <p class="intR1"><a href="/Home/ViewPage0">Home</a></p>
                <p class="intR1"><a href="/Home/ViewPage1">Traditional Culture</a></p>
                <p class="intR1"><a href="/Home/ViewPage2">Natural Scenery</a></p>
                <p class="intR1">@Html.ActionLink("Suggestion", "Index", "Feedbacks")</p>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
<style>
    .navbar-brand{
        margin-left:-10%;
    }
    .zujian div {
        display: inline;
    }
    /*页脚*/
    footer {
        margin-top: 22.5%;
        width: 136%;
        margin-left: -20%;
        height: 160px;
        background-color: grey;
        opacity: 0.8;
        display: flex;
        justify-content: space-around;
    }

    .introduceL {
        line-height: middle;
        margin-top: 1%;
        margin-left: -5%;
        text-decoration:none;
    }

    .introduceR {
        line-height: middle;
        margin-top: 0.5%;
        margin-right: 2vh;
        text-decoration: none;
    }

    .introduceL p {
        font-weight: 900;
        color: white;
        text-decoration: none;
    }

    .introduceR a {
        font-weight: 900;
        color: white;
        text-decoration: none;
    }

        .introduceR a:link,
        introduceR a:visited {
            color: #FFF;
            text-decoration: none;
        }

        .introduceR a:hover {
            color: #497271;
        }
    .introduce{
        margin-left:15%;
    }
    .introduce>ul{
        
        list-style:none;
        display:flex;
        justify-content:center;
        align-items:center;
         
    }
    .introduce ul li {
        
        font-weight:400;
        transition:all .5s linear;
        border-radius:20px;
        display:inline;
       color:#497271;

    }
    .introduce ul li a{
        color:white;
        text-decoration:none;
        padding-left:10px;
        padding-right:10px;
    }
    .introduce ul li:hover {
        background: #497271;
        color: #2b1055;
    }
    .four {
        background-color: #497271;
        border-radius: 20px;
        padding: 5px 10px;
    }
</style>
</html>

A2/A2/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="~/Content/Homenew.css" />
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

A2/A2/Views/Shared/_LayoutPage2.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/Culture.css" />
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

A2/A2/Views/Shared/_LayoutPage3.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/Scenery.css" />
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>